### PR TITLE
Add icon_prop_key support.

### PR DESCRIPTION
**Pull request by ikunya**
Ref: https://github.com/ibus/ibus/commit/23c45b970b195008a54884a1a9d810e7f8b22c5c

### CODE REVIEW

**Comment by ueno** [comment]
I really don't like the idea of modifying the document structure of an XML file with sed. Can't we simply assume ibus 1.5.11 and error out if the installed one is too old? I think the downstreams could adjust it if needed.

**Comment by ikunya** [comment]
Thank you for review.
This change is based on ibus-anthy and I think it is good idea.
I'll do another try later.

**Comment by ueno** [comment]
you promised to update the PR two months ago. what's the current status of it?

**Comment by ikunya** [comment]
I am very sorry. I have no time to take care.
Do you have any reason to hurry?

**Pull request closed without merging**
